server:
  port: 8086
logging:
  level:
    cc.au.hkzk: error
# mybatis
mybatis:
  type-aliases-package: cc.au.hkzk.entity

## SqlServer
spring:
    datasource:
      zk:
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        filters: stat,wall,slf4j
        initialSize: 5
        maxActive: 20
        maxPoolPreparedStatementPerConnectionSize: 20
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 5
        password: SS.9erver
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        url: jdbc:sqlserver://192.168.1.6:1433;database=zktime606_ID
        username: sa
        validationQuery: select 'x'
      hk:
        url: jdbc:postgresql://192.168.1.6:7017/acs_acsdb
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: PostG.9re
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        filters: stat,wall,slf4j
        initialSize: 5
        maxActive: 20
        maxPoolPreparedStatementPerConnectionSize: 20
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 5
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        validationQuery: select 'x'


